spring:
  application:
    name: ds-02

# 数据源配置
  datasource:
    ds1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds1?serverTimezone=UTC
      username: root
      password: root
    ds2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds2?serverTimezone=UTC
      username: root
      password: root
    ds3:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds3?serverTimezone=UTC
      username: root
      password: root

mybatis:
  mapper-locations: classpath*:mybatis/**/*.xml
server:
  port: 8081

