spring:
  application:
    name: ds-02

# \u6570\u636E\u6E90\u914D\u7F6E
# \u6570\u636E\u6E90ds1
  datasource:
    ds1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds1?serverTimezone=UTC
      username: root
      password: root
# \u6570\u636E\u6E90ds2
    ds2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds2?serverTimezone=UTC
      username: root
      password: root
# \u6570\u636E\u6E90ds3,\u4E3A\u9ED8\u8BA4\u6570\u636E\u6E90
    ds3:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ds3?serverTimezone=UTC
      username: root
      password: root

# mybatis\u914D\u7F6E
mybatis:
  mapper-locations: classpath*:mybatis/**/*.xml
server:
  port: 8081

